The interface of th eScikit Learn library is uniform, in the sense that we can use other learninig algorithms by calling the same functions.

The following piece of code illustrates that. Concretely, it applis KNeighborsClassifier, DecisionTreeClassifier, and SVC (Support Vector Classifier) algorithms to the Diabetes dataset. 

In [2]:
# Import necessary libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Define column names for the dataset
column_names = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome']

# Load the Pima Indians Diabetes dataset with column names
# Replace 'pima-indians-diabetes.csv' with the actual path to your dataset file
dataset = pd.read_csv('../data/pima-indians-diabetes.csv', names=column_names, header=0)

# Split the dataset into features (X) and the target variable (y)
X = dataset.drop('Outcome', axis=1)
y = dataset['Outcome']

# Split the data into a training set and a testing set (e.g., 70% training, 30% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Scale the features using StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Create and train the KNeighborsClassifier model
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train)

# Make predictions on the test set using KNeighborsClassifier
y_pred_knn = knn_model.predict(X_test)

# Evaluate the KNeighborsClassifier model
accuracy_knn = accuracy_score(y_test, y_pred_knn)
confusion_knn = confusion_matrix(y_test, y_pred_knn)
classification_rep_knn = classification_report(y_test, y_pred_knn)

# Create and train the DecisionTreeClassifier model
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)

# Make predictions on the test set using DecisionTreeClassifier
y_pred_dt = dt_model.predict(X_test)

# Evaluate the DecisionTreeClassifier model
accuracy_dt = accuracy_score(y_test, y_pred_dt)
confusion_dt = confusion_matrix(y_test, y_pred_dt)
classification_rep_dt = classification_report(y_test, y_pred_dt)

# Create and train the SVC (Support Vector Classifier) model
svc_model = SVC(kernel='linear', random_state=42)
svc_model.fit(X_train, y_train)

# Make predictions on the test set using SVC
y_pred_svc = svc_model.predict(X_test)

# Evaluate the SVC model
accuracy_svc = accuracy_score(y_test, y_pred_svc)
confusion_svc = confusion_matrix(y_test, y_pred_svc)
classification_rep_svc = classification_report(y_test, y_pred_svc)

# Print results for all three models
print("KNeighborsClassifier Results:")
print(f"Accuracy: {accuracy_knn * 100:.2f}%")
print("Confusion Matrix:\n", confusion_knn)
print("Classification Report:\n", classification_rep_knn)
print()

print("DecisionTreeClassifier Results:")
print(f"Accuracy: {accuracy_dt * 100:.2f}%")
print("Confusion Matrix:\n", confusion_dt)
print("Classification Report:\n", classification_rep_dt)
print()

print("SVC (Support Vector Classifier) Results:")
print(f"Accuracy: {accuracy_svc * 100:.2f}%")
print("Confusion Matrix:\n", confusion_svc)
print("Classification Report:\n", classification_rep_svc)


KNeighborsClassifier Results:
Accuracy: 70.13%
Confusion Matrix:
 [[125  26]
 [ 43  37]]
Classification Report:
               precision    recall  f1-score   support

           0       0.74      0.83      0.78       151
           1       0.59      0.46      0.52        80

    accuracy                           0.70       231
   macro avg       0.67      0.65      0.65       231
weighted avg       0.69      0.70      0.69       231


DecisionTreeClassifier Results:
Accuracy: 71.00%
Confusion Matrix:
 [[118  33]
 [ 34  46]]
Classification Report:
               precision    recall  f1-score   support

           0       0.78      0.78      0.78       151
           1       0.58      0.57      0.58        80

    accuracy                           0.71       231
   macro avg       0.68      0.68      0.68       231
weighted avg       0.71      0.71      0.71       231


SVC (Support Vector Classifier) Results:
Accuracy: 78.35%
Confusion Matrix:
 [[137  14]
 [ 36  44]]
Classification R