1. Centralize and normalize $\mathbf{X}$
2. Compute $\Sigma$, the covariance matrix of $\mathbf{X}$: $\Sigma = \frac{1}{m-1}\sum_{i=i}^{m} \left(\mathbf{x^{(i)}} \cdot \mathbf{x^{(i)}}^T\right)$
3. Decompose $\Sigma$ using SVD: $\Sigma = U S V^T$. The principal components are the columns of the matrix $U$.
4. Select the $k$ columns of $U$ corresponding to the $k$ largest singular values of $S$. These columns are the $k$ principal components.
5. Construct the Projection Matrix: $W = \left[u_1, u_2, \ldots, u_k\right]$
6. Project the data matrix over the basis formed by $U$: $\mathbf{X}_{\text{projected}} = \mathbf{X}W$

In [2]:
# %load ../src/pca.py
import numpy as np
from scipy import linalg as LA

def standardize(X):
    # Standardize the data matrix
    mean_X = np.mean(X, axis=0)
    std_X = np.std(X, axis=0)
    standardized_X = (X - mean_X) / std_X
    return standardized_X, mean_X, std_X

def svd(Sigma):
    U, S, V = LA.svd(Sigma)
    return U, S, V

def pca(X, k):
    Sigma = np.cov(X, rowvar = False)
    print(f'\nCovariance matrix:\n{Sigma}')

    U, S, V = svd(Sigma)

    print('\nPercentages of variation:\n', str(S/np.sum(S) * 100))

    # If we wish to reduce dimensionality to k, we first need to compute W
    W = U[:, 0:k]
    print('\nW (that is, truncated U):\n', str(W))

    # Now we compute X_projected, the matrix of projected points in k-dimensional space.
    X_projected = np.matmul(X, W)
    
    return X_projected, W

def reconstruct_data(X_projected, W):
    return np.matmul(X_projected, W.T)

In [3]:
# Data matrix X (four data points, each one is 3D)
X = np.array([
        [0.387,  4878, 5.42],
        [0.723, 12104, 5.25],
        [1,     12756, 5.52],
        [1.524,  6787, 3.94],
    ])

# Display the standardized data matrix
print("Original Data Matrix:")
print(X)

standardized_X, _, _ = standardize(X)

print("\nStandardized Data Matrix:")
print(standardized_X)

Original Data Matrix:
[[3.8700e-01 4.8780e+03 5.4200e+00]
 [7.2300e-01 1.2104e+04 5.2500e+00]
 [1.0000e+00 1.2756e+04 5.5200e+00]
 [1.5240e+00 6.7870e+03 3.9400e+00]]

Standardized Data Matrix:
[[-1.25237521 -1.2602333   0.60727372]
 [-0.44547575  0.88082256  0.34085686]
 [ 0.21973601  1.07400944  0.76398952]
 [ 1.47811494 -0.6945987  -1.7121201 ]]


In [12]:
# Data matrix X (four data points, each one is 3D)
X = np.array([
        [0.387,  4878, 5.42],
        [0.723, 12104, 5.25],
        [1,     12756, 5.52],
        [1.524,  6787, 3.94],
    ])

X, _, _ = standardize(X)

Sigma = np.cov(X, rowvar = False)
print(f'\nCovariance matrix:\n{Sigma}')

U, S, V = svd(Sigma)

print('U:\n' + str(U))
print('S:\n' + str(S))
print('V:\n' + str(V))

# Sanity check: verifying that eivenvectors are indeed unit vectors
print('\nNorms of eigenvectors (columns of U):')
print(np.linalg.norm(U[:,0]), np.linalg.norm(U[:,1]), np.linalg.norm(U[:,2]))

print('dot:\n')
print(np.dot(U[:,0], U[:,1]))



Covariance matrix:
[[ 1.33333333  0.1317339  -1.09173744]
 [ 0.1317339   1.33333333  0.51489873]
 [-1.09173744  0.51489873  1.33333333]]
U:
[[-0.64926351 -0.42018576  0.63395648]
 [ 0.24566452 -0.90471598 -0.34804876]
 [ 0.71979569 -0.07023474  0.69062381]]
S:
[2.49382602 1.43448827 0.07168571]
V:
[[-0.64926351  0.24566452  0.71979569]
 [-0.42018576 -0.90471598 -0.07023474]
 [ 0.63395648 -0.34804876  0.69062381]]

Norms of eigenvectors (columns of U):
0.9999999999999997 0.9999999999999999 0.9999999999999999
dot:

-4.0939474033052647e-16


In [9]:
( 2.49382602 + 1.43448827) / (2.49382602 + 1.43448827 + 0.07168571)



0.9820785725000001

In [5]:
# Data matrix X (four data points, each one is 3D)
X = np.array([
        [0.387,  4878, 5.42],
        [0.723, 12104, 5.25],
        [1,     12756, 5.52],
        [1.524,  6787, 3.94],
    ])

X, _, _ = standardize(X)    

print('\nX:\n' + str(X))

# Reduces the dimensionality from 3D to 2D.
k=2
X_projected, _ = pca(X, k)

print('\nX_projected (k=' + str(k) + '):\n' + str(X_projected))



X:
[[-1.25237521 -1.2602333   0.60727372]
 [-0.44547575  0.88082256  0.34085686]
 [ 0.21973601  1.07400944  0.76398952]
 [ 1.47811494 -0.6945987  -1.7121201 ]]

Covariance matrix:
[[ 1.33333333  0.1317339  -1.09173744]
 [ 0.1317339   1.33333333  0.51489873]
 [-1.09173744  0.51489873  1.33333333]]

Percentages of variation:
 [62.34565042 35.8622068   1.79214278]

W (that is, truncated U):
 [[-0.64926351 -0.42018576]
 [ 0.24566452 -0.90471598]
 [ 0.71979569 -0.07023474]]

X_projected (k=2):
[[ 0.94063993  1.62373172]
 [ 0.7509653  -0.63365168]
 [ 0.6710958  -1.11766206]
 [-2.36270102  0.12758202]]


In [6]:
X = np.array([
        [0.387,  4878, 5.42],
        [0.723, 12104, 5.25],
        [1,     12756, 5.52],
        [1.524,  6787, 3.94],
    ])

X, _, _ = standardize(X)    
print('\nX:\n' + str(X))

X_projected, W = pca(X, k=2)

reconstruct_data(W, X_projected)

print('\nX_reconstructed:\n' + str(np.matmul(X_projected, W.T)))


X:
[[-1.25237521 -1.2602333   0.60727372]
 [-0.44547575  0.88082256  0.34085686]
 [ 0.21973601  1.07400944  0.76398952]
 [ 1.47811494 -0.6945987  -1.7121201 ]]

Covariance matrix:
[[ 1.33333333  0.1317339  -1.09173744]
 [ 0.1317339   1.33333333  0.51489873]
 [-1.09173744  0.51489873  1.33333333]]

Percentages of variation:
 [62.34565042 35.8622068   1.79214278]

W (that is, truncated U):
 [[-0.64926351 -0.42018576]
 [ 0.24566452 -0.90471598]
 [ 0.71979569 -0.07023474]]

X_reconstructed:
[[-1.29299213 -1.23793419  0.56302618]
 [-0.22132296  0.75776033  0.58504595]
 [ 0.03390767  1.17603116  0.56155057]
 [ 1.48040742 -0.6958573  -1.7096227 ]]


What do you expect the projected datasets would be for the data matrix X? Explain the results for k=3 and k = 1. Compare with the results obtained in the cell above.

In [7]:
X1 = np.array([
        [1,   2, -.05],
        [2,   4, -.05],
        [4,   8, -.05],
        [8,  16, -.05],
    ])
pca(X=X1, k=3)
pca(X=X1, k=1)


Covariance matrix:
[[ 9.58333333 19.16666667  0.        ]
 [19.16666667 38.33333333  0.        ]
 [ 0.          0.          0.        ]]

Percentages of variation:
 [1.00000000e+02 1.32632086e-14 0.00000000e+00]

W (that is, truncated U):
 [[-0.4472136  -0.89442719  0.        ]
 [-0.89442719  0.4472136   0.        ]
 [ 0.          0.          1.        ]]

Covariance matrix:
[[ 9.58333333 19.16666667  0.        ]
 [19.16666667 38.33333333  0.        ]
 [ 0.          0.          0.        ]]

Percentages of variation:
 [1.00000000e+02 1.32632086e-14 0.00000000e+00]

W (that is, truncated U):
 [[-0.4472136 ]
 [-0.89442719]
 [ 0.        ]]


(array([[ -2.23606798],
        [ -4.47213595],
        [ -8.94427191],
        [-17.88854382]]),
 array([[-0.4472136 ],
        [-0.89442719],
        [ 0.        ]]))