In [1]:
import torch

In [2]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [4]:
y = x - 2
print(y)

tensor([[-1., -1.],
        [-1., -1.]], grad_fn=<SubBackward>)


In [6]:
z = 2 * y
print(z)

tensor([[-2., -2.],
        [-2., -2.]], grad_fn=<MulBackward>)


In [7]:
print(z.grad_fn)

In [11]:
w = z * z * 3
out = z.mean()
print(w, out)
print(out)

tensor([[12., 12.],
        [12., 12.]], grad_fn=<MulBackward>) tensor(-2., grad_fn=<MeanBackward1>)
tensor(-2., grad_fn=<MeanBackward1>)


In [12]:
out.backward()

In [13]:
print(x.grad)

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])
